### ISSUE TITLE
Parsing Less Functions containing default values gets interpreted as Pseudo-Elements

### ISSUE THREAD

**Issue by julkuh** [racodond/sonar-css-plugin#10]
Hey,

parsing less functions containing default values for params (e.g.`@animation-count:infinite`) results in  a Major SonarQube issue 

> Remove this usage of the unknown "linear" pseudo. 

LESS-Sample
```css
.animation (@animation-name, @animation-duration, @animation-count:infinte, @timing-function:linear){
   -webkit-animation: @animation-name @animation-duration @animation-count @timing-function;
    animation: @animation-name @animation-duration @animation-count @timing-function;
}
```
