### ISSUE TITLE
@keyframes should no longer be set to experimental

### ISSUE THREAD

**Issue by julkuh** [racodond/sonar-css-plugin#12]
CSS3 Keyframe Definitions (see sample below, which is [W3C compliant](https://www.w3.org/TR/css3-animations/#animations)) are interpreted as experimental rules and result therefore in a **major issue**
```css

@keyframes FadeIn {   
    from {opacity:0;}
    to {opacity:1;}
}
```
