### ISSUE TITLE
Throws an error with special characters

### ISSUE THREAD

**Issue by Tiberriver256** [racodond/sonar-css-plugin#121]
Example:
```css
.icon-save:before {
        content: '✔';
    }
```

Will cause the following error:
```
org.sonar.squidbridge.api.AnalysisException: Unable to analyze file
```
