### ISSUE TITLE
LESS: Minus ('-') is wrongly considered as unknown function

### ISSUE THREAD

**Issue by salixzs** [racodond/sonar-css-plugin#67]
SonarQube server version 6.4.0.25310
CSS / SCSS / Less plugin, version 4.5

I receive this violation:
**Remove this usage of the unknown "-" function.**
It is reported as "_Unknown CSS / Less functions should be removed_" violation.
LESS code piece is actually normally compiling and working code:
```css
.step-marker {
    top: -(@timeline-h-size-step/2)-(@timeline-h-size-line/2);
}
```
(both minus signs are reported as unknown function.)
